import axios from "axios";
import { Header } from "./components/Header";
import { CartProvider } from '@/context/CartContext'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = await axios.get('http://localhost:3000/api/cart-items?expand=product');
  const cart = response.data
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
        <CartProvider>
          <Header />
          {children}
        </CartProvider>
        
      </body>
    </html>
  );
}
